### ISSUE TITLE
Error with protractor

### ISSUE THREAD

**Issue by gpincheiraa** [mrsheepuk/docker-protractor#1]
HI
I've been trying to use this docker and when i execute  **docker run** i get this error:

> /usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
>   'Supervisord is running as root and it is searching '
> 2016-07-14 21:08:13,639 CRIT Supervisor running as root (no user in config file)
> 2016-07-14 21:08:13,639 WARN Included extra file "/etc/supervisor/conf.d/xvfb.conf" during parsing
> 2016-07-14 21:08:13,639 WARN Included extra file "/etc/supervisor/conf.d/webdriver.conf" during parsing
> 2016-07-14 21:08:13,639 WARN Included extra file "/etc/supervisor/conf.d/protractor.conf" during parsing
> 2016-07-14 21:08:13,645 INFO RPC interface 'supervisor' initialized
> 2016-07-14 21:08:13,645 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> 2016-07-14 21:08:13,645 INFO supervisord started with pid 1
> 2016-07-14 21:08:14,647 INFO spawned: 'webdriver' with pid 8
> 2016-07-14 21:08:14,650 INFO spawned: 'xvfb' with pid 9
> 2016-07-14 21:08:14,651 INFO spawnerr: command at '/usr/local/bin/run-protractor' is not executable
> 2016-07-14 21:08:16,044 INFO success: webdriver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-07-14 21:08:16,044 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 2016-07-14 21:08:16,045 INFO spawnerr: command at '/usr/local/bin/run-protractor' is not executable
> 2016-07-14 21:08:18,047 INFO spawnerr: command at '/usr/local/bin/run-protractor' is not executable
> 2016-07-14 21:08:21,052 INFO spawnerr: command at '/usr/local/bin/run-protractor' is not executable
> 2016-07-14 21:08:21,052 INFO gave up: protractor entered FATAL state, too many start retries too quickly

**Comment by stefanvangastel** [comment]
Same

**Comment by mrsheepuk** [comment]
Hi @stefanvangastel @gpincheiraa I've incorporated the latest changes from the source project into this fork now, made a few other tweaks, and ensured that the run-protractor file is executable. Can you give it another go and let me know if it's working for you now?

**Comment by mrsheepuk** [comment]
Closing due to believing this fixed, please let me know if it's not working still.
