### ISSUE TITLE
Npm version out of date

### ISSUE THREAD

**Issue by Garbett1** [mrsheepuk/docker-protractor#4]
The install script installs an old version of NPM due to the version being stored in the apt repo being old.

This can cause issues with trying to rely of newer features of NPM, such as @<package name> scoping (Such as @Angular or @Types).

I think a solution could be using a a curl script to pull a newer version.

**Comment by mrsheepuk** [comment]
Great point @Garbett1 , I've added in an "npm install -g npm" step to update to the latest NPM after installing the packaged version, that should address this. Give it a try and let me know if it's resolved the issue for you!

**Comment by Garbett1** [comment]
Npm seems to be installing fine, great!

**Comment by mrsheepuk** [comment]
Great, thanks for confirming.
