### ISSUE TITLE
Error /tmp/deb-multimedia-keyring_2015.6.1_all.deb' is not a debian format archive

### ISSUE THREAD

**Issue by devdavidkarlsson** [mrsheepuk/docker-protractor#5]
Step 4 : RUN curl http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.3.7_all.deb   -o /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   dpkg -i /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   rm /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   echo "deb http://www.deb-multimedia.org stretch main non-free" >> /etc/apt/sources.list
 ---> Running in 4f30327e1025
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4420  100  4420    0     0    775      0  0:00:05  0:00:05 --:--:--  1058
dpkg-deb: error: '/tmp/deb-multimedia-keyring_2015.6.1_all.deb' is not a debian format archive
dpkg: error processing archive /tmp/deb-multimedia-keyring_2015.6.1_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /tmp/deb-multimedia-keyring_2015.6.1_all.deb
The command '/bin/sh -c curl http://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.3.7_all.deb   -o /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   dpkg -i /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   rm /tmp/deb-multimedia-keyring_2015.6.1_all.deb &&   echo "deb http://www.deb-multimedia.org stretch main non-free" >> /etc/apt/sources.list' returned a non-zero code: 1

**Comment by mrsheepuk** [comment]
This was fixed back in September, if you clone / pull the latest version, this should work perfectly. Closing for now, but if you have any further problems please comment back!
