### ISSUE TITLE
What is the License?

### ISSUE THREAD

**Issue by pulkitsinghal** [mrsheepuk/docker-protractor#9]
Hello what license does this project fall under?
It would be great if you could add a license file that clarifies this: https://choosealicense.com/

Thanks!

**Comment by mrsheepuk** [comment]
It's a fair question - I'm happy for it to be considered MIT licensed, I'll add the licence file when I get a chance.

**Comment by pulkitsinghal** [comment]
Super Cool! Thanks for that @mrsheepuk 
I shall await the changes eagerly so that I too may reflect them in my fork.

**Comment by tangentlin** [comment]
Hi, we are thinking of adopting your solution in our organization for test automation, but our organization only allows MIT or Apache license.  @mrsheepuk, when do you think you could add the license file?

**Comment by pulkitsinghal** [comment]
Hello @tangentlin 

Since @mrsheepuk's contribution, there have been official and well supported container images released directly by [SeleniumHQ/docker-selenium](https://github.com/SeleniumHQ/docker-selenium/):
- you can run selenium server and browser in one container
- you can run your protractor test runner in another container
- you can even attach to a VNC session and watch what the browser is doing inside the container!

But this project is still quite useful as learning material:
- when you wish to hack together a container image with java and its elusive ffmpeg dependency
- when you need references/examples of how supervisor can help keep containers alive
